version: '3.8'

services:
  app:
    build: .
    image: vigneshkumard2797/retail-edge:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: chat_app_xx2k_user
      SPRING_DATASOURCE_PASSWORD: 7ALfodDEB5k3Cx2A2RjQlr3KMo8uLsen
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cusl315svqrc73du1nng-a.oregon-postgres.render.com:5432/chat_app_xx2k
    ports:
      - "8080:8080"
    restart: on-failure

